### ISSUE TITLE
Potential false positive: variable used in multiple if statements

### ISSUE THREAD

**Issue by sbueringer** [esimonov/ifshort#23]
I'm not sure if it's intentional but the following code produces a finding:

```go
	isDeleteNodeAllowed := err == nil

	if isDeleteNodeAllowed {
		fmt.Println("abc")
	}

	if isDeleteNodeAllowed {
		fmt.Println("def")
	}
```

```bash
controllers/machine_controller.go:278:2: variable 'isDeleteNodeAllowed' is only used in the if-statement (controllers/machine_controller.go:280:2); consider using short syntax (ifshort)
        isDeleteNodeAllowed := err == nil
        ^
```
(full original code can be seen [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/machine_controller.go#L276), but the short version above also produces the finding)

In case it's not intentional, I think the problem is that `getNamedOccurrenceMap=>addFromCondition` only adds one occurrence for the first if. The second if is not added as additional occurrence because `addFromIdent=>occ.isComplete` returns true.

Interestingly this issue is only reported in ~90-95% of the cases when ifshort is run.

Context: We are running ifshort via golangci-lint and we are also running the nolint linter.
For some reason that finding (on the original code) is not reported on every run. We've added a nolint statement, but in those cases where ifshort does not report the finding we'll get a finding that the nolint statement is not required.

**Comment by esimonov** [comment]
Could you please advise what version of golangci-lint are you using? I ran v1.42.1 on the following function ten times in a row and it didn't report any findings. 
```go
func notUsed_IfStmt_MultipleIfStmt_OK() {
	err := getValue()
	isDeleteNodeAllowed := err == nil

	if isDeleteNodeAllowed {
		fmt.Println("abc")
	}

	if isDeleteNodeAllowed {
		fmt.Println("def")
	}
}
```

**Comment by sbueringer** [comment]
I'm using `v1.43.0`

**Comment by sbueringer** [comment]
Sorry as a full example:
```go
package main

import (
	"fmt"
)

func main() {

	err := fmt.Errorf("test")

	isDeleteNodeAllowed := err == nil

	if isDeleteNodeAllowed {
		fmt.Println("abc")
	}

	if isDeleteNodeAllowed {
		fmt.Println("def")
	}
}
```

```bash

main.go:11:2: variable 'isDeleteNodeAllowed' is only used in the if-statement (main.go:13:2); consider using short syntax (ifshort)
        isDeleteNodeAllowed := err == nil
```

**Comment by Walz** [comment]
I encountered a similar issue, I've been able to reproduce it with the following code:
main.go
```
package main

func main() {
	x := 0

	for i := 0; i < 10; i++ {
		if i%2 == 0 {
			continue
		} else {
			x++
		}
	}

	if x > 0 {
		println(x)
	}
}
```

And the output of `golangci-lint`:
```
main.go:5:2: variable 'x' is only used in the if-statement (cmd/main.go:15:2); consider using short syntax (ifshort)
	x := 0
	^
```

`x`  is used in the `else` and the second `if`.  
I'm using `golangci-lint 1.43.0`.

**Comment by korya** [comment]
Another case where a similar false positive occurs:

```go
err := doSomething()

doSomethingElse()

if err != nil {
    fmr.Printf("Failed: %s\n", err)
}
```

I am using `golangci-lint v1.43.0` as well.
