### ISSUE TITLE
false positive: used in return value

### ISSUE THREAD

**Issue by carldunham** [esimonov/ifshort#9]
Not sure if this case is covered already:
```
func examples() []string {
	field := os.Getenv("FIELD")
	if field == "" {
		field = "foo"
	}
	return []string{field}
}
```
results in:
```
variable 'field' is only used in the if-statement (example.go:2:2); consider using short syntax (ifshort)
        field := t.Field
        ^
```
This is the shortest example I could boil down to, but found the issue using `field` as a map key, and in other ways in the return. Not sure if these are all the same issue, happy to provide more examples.

**Comment by esimonov** [comment]
Thank you!
The fix is included in `v1.0.2`.
